# Generated by Django 5.0.7 on 2024-07-21 23:59

import django.utils.timezone
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True, verbose_name='TRACKER ID')),
                ('sender_name', models.CharField(max_length=50)),
                ('sender_phone', models.IntegerField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_address', models.CharField(max_length=80)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_phone', models.IntegerField()),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_address', models.CharField(max_length=80)),
                ('parcel_description', models.CharField(max_length=200)),
                ('dispatch_location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('In transit', 'Intransit'), ('Picked Up', 'Picked'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('On Hold', 'Onhold')], default='In transit', max_length=15)),
                ('dispatch_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField()),
                ('current_location', models.CharField(max_length=200)),
            ],
        ),
    ]
